feat: Ratings of Events and Users
SergeyMont/java-explore-with-me pull request #3
Opened 2022-10-03 12:44 UTC by SergeyMont

2022-10-05 10:13 UTC, vbutrim commented on server/src/main/java/ewm/user/service/UserService.java
> +    public List<UserShortDto> getAllUsers() {
сервис должен возвращать доменный объект и никак не dto

2022-10-05 10:18 UTC, vbutrim commented on server/src/main/java/ewm/event/service/RatingService.java
> +        if (rating < 0 || rating > 10) throw new BadConditionException("Рейтинг должен быть от 0 до 10");
[nit] 0, конечно, -- странная оценка)

2022-10-05 10:18 UTC, vbutrim commented on server/src/main/java/ewm/event/service/RatingService.java
> +                eventRepository.findById(eventId).get(),
[nit] `.orElseThrow(() -> кастомный_эксепшен)`

примено здесь и дальше

2022-10-05 10:19 UTC, vbutrim commented on server/src/main/java/ewm/event/controller/RatingController.java
> +    @DeleteMapping("/users/rating")
[nit] точно ли нужно удалять проставленный рейтинг? 🤔

2022-10-05 10:21 UTC, vbutrim commented on server/src/main/java/ewm/event/controller/RatingController.java
> +    @PostMapping("/users/rating")
рейтинг с развитием проекта может быть проставлен не только на event.
я бы ввел один единственный эндпоинт

PATCH: /events/{eventId}/rate, что является идемпотентным

2022-10-05 10:21 UTC, vbutrim commented on server/src/main/java/ewm/event/controller/RatingController.java
> +@AllArgsConstructor
[nit] @RequestMapping

2022-10-05 10:22 UTC, vbutrim commented on server/src/main/java/ewm/event/EventRatingKey.java
> +    }
[nit] lombok's Data уже содержит eventId и hashCode

2022-10-05 10:23 UTC, vbutrim commented on server/src/main/java/ewm/user/service/UserService.java
> +    public List<UserShortDto> getAllUsers() {
_применимо здесь и дальше_

2022-10-05 10:23 UTC, vbutrim commented on server/src/main/java/ewm/event/service/EventService.java
> +        //setup Rating
[nit] ненужный комментарий

2022-10-05 10:25 UTC, vbutrim commented on server/src/main/java/ewm/event/service/EventService.java
> +                //add sort by Rating
[nit] ненужный комментарий

2022-10-05 10:26 UTC, vbutrim commented on server/src/main/java/ewm/event/service/EventService.java
> +                .sorted(Comparator.comparing(EventFullDto::getRating).reversed())
в пользу того, что сервис должен оперировать доменными объектами, а не dto.
здесь ты оперириуешь dto, а не доменными объектами: что не круто

2022-10-05 10:26 UTC, vbutrim requested changes
оставил несколько замечаний

2022-10-05 20:19 UTC, drumer32 commented on server/src/main/java/ewm/event/service/RatingService.java
> +        if (rating < 0 || rating > 10) throw new BadConditionException("Рейтинг должен быть от 0 до 10");
а я бы оставил

2022-10-05 20:21 UTC, drumer32 approved these changes

2022-10-07 07:21 UTC, SergeyMont commented on server/src/main/java/ewm/event/EventRatingKey.java
> +    }
Да, только именно в данном случае нужно жестко прописывать, иначе не заведется.
Note that a composite key class has to fulfill some key requirements:

We have to mark it with @Embeddable.
It has to implement java.io.Serializable.
We need to provide an implementation of the hashcode() and equals() methods.
None of the fields can be an entity themselves.
https://www.baeldung.com/jpa-many-to-many

2022-10-07 07:23 UTC, SergeyMont commented on server/src/main/java/ewm/event/service/EventService.java
> +        //setup Rating
Добавил для ревью

2022-10-07 07:23 UTC, SergeyMont commented on server/src/main/java/ewm/event/service/EventService.java
> +                //add sort by Rating
Добавлено только для ревью

2022-10-07 07:30 UTC, SergeyMont commented on server/src/main/java/ewm/event/service/RatingService.java
> +        if (rating < 0 || rating > 10) throw new BadConditionException("Рейтинг должен быть от 0 до 10");
Если можно поставить максимальную оценку, то и минимальная допустима. Иногда даже делают интервал -5 до +5. Оставил как есть.

2022-10-07 07:35 UTC, SergeyMont commented on server/src/main/java/ewm/event/service/RatingService.java
> +                eventRepository.findById(eventId).get(),
fix

2022-10-07 07:39 UTC, SergeyMont commented on server/src/main/java/ewm/event/controller/RatingController.java
> +@AllArgsConstructor
fix

2022-10-07 07:48 UTC, SergeyMont commented on server/src/main/java/ewm/event/service/EventService.java
> +                .sorted(Comparator.comparing(EventFullDto::getRating).reversed())
Но в доменном объекте Эвента нет поля с рейтингом, это расчетное поле исходя из таблицы рейтинга. Мне кажется резонным прикрутить эту опцию к Дто объекту без изменения основной схемы базы и доменных объектов.

2022-10-07 07:58 UTC, SergeyMont commented on server/src/main/java/ewm/event/controller/RatingController.java
> +    @DeleteMapping("/users/rating")
Добавил такую возможность.

2022-10-07 08:05 UTC, SergeyMont commented on server/src/main/java/ewm/event/controller/RatingController.java
> +    @PostMapping("/users/rating")
fix

2022-10-07 08:09 UTC, SergeyMont commented on server/src/main/java/ewm/user/service/UserService.java
> +    public List<UserShortDto> getAllUsers() {
Но если мы вернем доменный объект, там будут почты пользователей, а это совсем не хорошо. По этому и возвращаю из сервиса на контроллер ДТО.

2022-10-07 15:44 UTC, vbutrim commented on server/src/main/java/ewm/event/service/EventService.java
> +                .sorted(Comparator.comparing(EventFullDto::getRating).reversed())
> в доменном объекте Эвента нет поля с рейтингом,

ты ведь может сделать доменным объект "событие с рейтингом"

2022-10-07 15:46 UTC, vbutrim commented on server/src/main/java/ewm/user/service/UserService.java
> +    public List<UserShortDto> getAllUsers() {
> Но если мы вернем доменный объект, там будут почты пользователей, а это совсем не хорошо

почему? речь про возвращаемый объект из сервиса, а не API

2022-10-10 07:31 UTC, SergeyMont commented on server/src/main/java/ewm/user/service/UserService.java
> +    public List<UserShortDto> getAllUsers() {
fix

2022-10-10 10:11 UTC, SergeyMont commented on server/src/main/java/ewm/event/service/EventService.java
> +                .sorted(Comparator.comparing(EventFullDto::getRating).reversed())
fix

2022-11-05 08:03 UTC, merged